### ISSUE TITLE
Slight overflow

### ISSUE THREAD

**Issue by JonathanGin52** [OOQQ/OOQQ#1]
Love the meme haha. There is a tiny amount of overflow, which is causing a horizontal scroll bar to apear. There isn't too much happening on the left, so parts of it can probably be removed to get around this issue

![image](https://user-images.githubusercontent.com/26397946/87899317-cf104100-ca1e-11ea-84c7-33cf0361e987.png)

**Comment by esparade** [comment]
Unfortunately since the div container is flexible, it depends on the screen resolution.
